services:
  - type: web
    name: ai-dungeon-master
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend:app
    # envVars:
    #   - key: PYTHON_VERSION
    #     value: 3.11.0